name: Increment Patch Version

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - release

jobs:
  increment-patch-version:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version numbers
        run: |
          current_version=$(cat VERSION)
          current_version=${current_version//[^0-9.]/}
          major=${current_version%%.*}
          minor_patch=${current_version#*.}
          minor=${minor_patch%%.*}
          patch=${minor_patch#*.}
          echo "major=$major" >> $GITHUB_ENV
          echo "minor=$minor" >> $GITHUB_ENV
          echo "patch=$patch" >> $GITHUB_ENV
      - name: Increment patch version
        run: |
          new_patch=$((patch + 1))
          new_version="${major}.${minor}.${new_patch}"
          echo "new_version=$new_version" >> $GITHUB_ENV
      - name: Write version to file
        run: |
          echo "$new_version" > VERSION
      - name: Write to changelog
        run: |
          date=$(date '+%Y-%m-%d')
          msg="$date $new_version: ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}"
          echo "$msg" >> CHANGELOG
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add VERSION
          git add CHANGELOG
          git commit -m "Github action: increment version and update changelog"
          git push origin ${{ github.ref_name }}
