name: Increment version and create changelog

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - release

jobs:
  increment-version-and-create-changelog:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version numbers
        run: |
          current_version=$(cat VERSION)
          current_version=${current_version//[^0-9.]/}
          major=${current_version%%.*}
          minor_patch=${current_version#*.}
          minor=${minor_patch%%.*}
          patch=${minor_patch#*.}
          echo "major=$major" >> $GITHUB_ENV
          echo "minor=$minor" >> $GITHUB_ENV
          echo "patch=$patch" >> $GITHUB_ENV
      - name: Increment version
        run: |
          if [[ "${{ github.event.pull_request.title }}" == feature* ]]; then
            ((minor++)) || true
          else
            ((patch++)) || true
          fi
          new_version="${major}.${minor}.${patch}"
          echo "new_version=$new_version" >> $GITHUB_ENV
      - name: Write version to file
        run: |
          echo "$new_version" > VERSION
      - name: Write to changelog
        run: |
          date=$(date '+%Y-%m-%d')
          msg="$date $new_version: ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}"
          echo "$msg" >> CHANGELOG
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # To allow push: Your Github project > Settings > Actions > General > Workflow permissions
        run: |
          git config --global user.email "alfred@avalor.ai"
          git config --global user.name "Alfred"
          git add VERSION
          git add CHANGELOG
          git commit -m "Github action: increment version and update changelog"
          git push origin ${{ github.ref_name }}
